---
title: "Approfondimenti"
format: html 
toc: true
toc-location: left
---


## Intervista al Direttore

### 1. Prof. Claudio Sica, cosa si intende per “Meditazione, compassione e gestione emozionale”?

**R:** L’esperienza clinica e i recenti studi delle neuroscienze stanno confermando l’importanza della pratica meditativa sia sul versante delle capacità di attenzione e consapevolezza sia sul versante della trasformazione delle emozioni distruttive e dello sviluppo degli stati mentali costruttivi. L’integrazione delle esperienze derivate dalle pratiche contemplative con la psicologia clinica offre strumenti specifici atti a favorire una migliore comprensione degli stati emotivi e della loro gestione sia nel professionista della relazione di aiuto (psicologo, medico, infermiere, educatore, insegnante, responsabili risorse umane, ecc.) che nelle persone oggetto dell’intervento dei professionisti. Le tecniche contemplative e la psicologia centrata sugli stati di accettazione e compassione e di sintonizzazione relazionale permettono di acquisire e affinare un’attitudine di attenzione e sintonizzazione empatica per una maggiore efficacia dell’intervento clinico ed educativo. Tale attitudine rappresenta il fattore centrale trasversale a diversi modelli teorico-operativi ed è il fondamento di una matura capacità di prendersi cura di sé e di relazionarsi agli altri in modo empatico ed equilibrato.

### 2. Come si sviluppa il percorso didattico del Corso?

Ogni tematica viene approfondita sul piano teorico e sul piano operativo attraverso l’utilizzo di tecniche e strumenti provenienti dalle tradizioni contemplative, dalla Mindfulness, e da quelle correnti della psicologia che enfatizzano le capacità relazionali e di gestione emozionale dell’individuo. Il formato del corso avrà un carattere spiccatamente esperienziale in modo da consentire un apprendimento diretto dei contenuti e delle pratiche meditative e interpersonali proposte. Attraverso il potere equilibrante e benefico della presenza mentale e degli stati mentali costruttivi ogni partecipante avrà la possibilità di sperimentare direttamente il rapporto tra schemi cognitivi, stati emotivi e dimensione corporea. Il lavoro di gruppo durante i tre residenziali presso l’Istituto Lama-Tzong Khapa di Pomaia (il più grande istituto europeo di studi e formazione buddista) favorisce lo sviluppo e un confronto delle esperienze emotive e relazionali. Inoltre, la presenza di docenti e monaci con la massima esperienza nei modelli buddisti e psicologici della mente garantisce una formazione di assoluto rigore in tempi molto brevi.

### 3. A chi è rivolto?

A tutti i professionisti il cui lavoro è orientato e centrato sull’aiuto o sullo sviluppo anche di aspetti relazionali, emotivi e sociali: insegnanti, medici, infermieri, psicologi, educatori, responsabili di uffici di risorse umane. **IMPORTANTE:** il percorso è adatto comunque a chiunque voglia approfondire in modo rigoroso le tematiche più moderne che connettono gli aspetti psicologico-relazionali alle pratiche sviluppate nel buddismo. Il corso nasce sotto gli auspici dell’UBI, l’Unione Buddhista Italiana, l’organo ufficiale italiano che raccoglie gli istituti di formazione buddista più importanti del nostro paese. Essendo un corso di perfezionamento universitario che produce un diploma finale, è richiesta obbligatoriamente una laurea di un qualsiasi genere, anche di primo livello (Triennale).

### 4. Quali competenze si acquisiscono?

Alcune delle competenze riguardano: le pratiche buddiste di meditazione e compassione, le capacità di concentrazione e consapevolezza nella pratica meditativa, la conoscenza di alcuni processi emotivi, le tecniche focalizzate sulla compassione e sulla accettazione, le conoscenze più aggiornate sulla ricerca psicologica sulla mindfulness e la sua misura. Alla fine del corso, nell’ultimo residenziale, viene richiesto di condividere e discutere un progetto esistenziale o professionale che includa le competenze acquisite.

### 5. Quali prospettive occupazionali ci sono per chi partecipa al Corso di Perfezionamento?

Il corso offre in un formato agile ma intensivo competenze trasversali che si rivelano fondamentali per lo sviluppo umano e professionale di tutti i rapporti interpersonali e per il miglioramento delle capacità nell’ambito delle relazioni di aiuto.

## Materiali dei docenti

- [Il processo emotivo e la correlazione mente/corpo](materials/gusmano_1.docx) (Massimo Gusmano)
- [BRAHMA VIHARA (I QUATTRO INCOMMENSURABILI O DIMORE DIVINE)](materials/gusmano_2.docx) (Massimo Gusmano)
- [Training cognitivo e contemplativo per lo sviluppo della compassione](https://ccaudek.github.io/perfezionamento/) (Corrado Caudek)


