---
title: "Domande frequenti"
format: html 
toc: true
toc-location: left
---


Hai qualche dubbio? Consulta le nostre domande frequenti.

**Quali documenti vengono rilasciati al termine del Corso?**

Attestato di partecipazione universitario e attestazione dei crediti ECM acquisiti.

**Come possono essere utilizzate le competenze acquisite nel Corso nella tua attività professionale?**

- *Claudio Sica.* Il corso di perfezionamento in "Meditazione, compassione e gestione emozionale per le professioni di aiuto" si basa su insegnamenti profondi del buddhismo mahayana, tecniche contemplative e meditazione, e sull'integrazione tra psicologia e buddhismo. Queste discipline offrono un insieme di strumenti preziosi per chi opera nelle professioni di aiuto, dove la gestione delle emozioni e delle situazioni di forte impatto emotivo è fondamentale. Le attività del corso sono state strutturate per fornirvi competenze pratiche e applicabili nel vostro ambito professionale. Attraverso esercizi di meditazione, pratiche di compassione e tecniche di gestione delle emozioni, imparerete non solo a gestire meglio lo stress e le difficoltà quotidiane del vostro lavoro, ma anche a migliorare la qualità delle relazioni interpersonali e a promuovere il benessere sia vostro che dei vostri clienti. Le competenze che acquisirete nel corso di perfezionamento in "Meditazione, compassione e gestione emozionale per le professioni di aiuto" sono progettate per avere applicazioni pratiche e tangibili nel vostro lavoro quotidiano. Ecco come:

    1. Gestione dello Stress e delle Emozioni: Immaginate di lavorare con un cliente che sta vivendo una crisi emotiva. Utilizzando le tecniche di meditazione e gestione delle emozioni apprese, sarete in grado di mantenere la calma, offrire una presenza rassicurante e guidare il cliente verso uno stato di maggiore tranquillità. Questo non solo migliora la qualità del supporto che offrite, ma anche la vostra capacità di sostenere emotivamente voi stessi.
    
    2. Miglioramento delle Relazioni Interpersonali: Le pratiche di compassione apprese possono trasformare le vostre interazioni con colleghi e clienti. Ad esempio, in una situazione di conflitto, applicare la meditazione di compassione vi aiuterà a comprendere meglio il punto di vista dell'altro, facilitando una risoluzione più empatica e costruttiva.
    
    3. Aumento della Consapevolezza e della Presenza: Durante una sessione di consulenza, essere pienamente presenti e consapevoli permette di cogliere sfumature importanti nei discorsi dei clienti, migliorando la qualità delle vostre risposte e delle strategie di intervento.
    
    4. Promozione della Resilienza e del Benessere Personale: Le tecniche di meditazione non solo aiutano a gestire lo stress professionale, ma anche a migliorare la vostra resilienza personale. Questo si traduce in una maggiore capacità di recupero dopo situazioni difficili e una miglior gestione
    del burnout.
    
    5. Sviluppo Umano e Mentale: Oltre alle applicazioni specifiche nel contesto professionale, le competenze acquisite contribuiscono significativamente al vostro sviluppo umano e mentale generale. La pratica regolare della meditazione e delle tecniche contemplative può portare a:
    - Miglioramento della Qualità della Vita: Riduzione dello stress quotidiano, maggiore equilibrio emotivo e un senso di pace interiore.
    - Crescita Personale: Sviluppo di una maggiore autoconsapevolezza, compassione per sé stessi e per gli altri, e un approccio più riflessivo alla vita.
    - Miglioramento delle Capacità Cognitive: Aumento della capacità di concentrazione, chiarezza mentale e capacità di prendere decisioni ponderate.
    
    Conclusione: Le competenze acquisite nel corso non solo arricchiranno la vostra pratica professionale,
    rendendovi più efficaci e resilienti nel vostro lavoro, ma avranno anche un impatto positivo e duraturo sulla vostra vita personale. Sfruttando queste abilità, diventerete professionisti più
    consapevoli, empatici e capaci di gestire le sfide emotive con maggiore efficacia e serenità.

- *Corrado Caudek.* Nelle professioni di aiuto, una delle questioni cruciali è la perdita di significato che può derivare da crisi personali, economiche, culturali o sociali. Il mio intervento  propone una risposta spirituale a questa perdita, non vincolata a dogmi religiosi o scientifici, ma basata su una spiritualità universale. Attraverso esempi tratti dalla filosofia Madhyamaka del Buddhismo tibetano, il mio intervento esplora come l'assenza percepita di significato possa essere trasformata in una comprensione profonda e contemplativa dell'esistenza. Gli operatori delle professioni di aiuto apprenderanno come tradurre questi concetti in un linguaggio contemporaneo e psicologicamente rilevante. Questo approccio fornisce una formazione avanzata che integra riflessioni spirituali e tecniche psicologiche moderne, migliorando le competenze professionali e l'efficacia degli interventi.

**Sono previste agevolazioni economiche per l'iscrizione al Corso?**

I costi coprono l’affitto dei locali di Pomaia e il pagamento docenti e sono quindi molto
contenuti. Per questo motivo non è possibile offrire borse di studio.

**Il costo di iscrizione include anche il pernottamento a Pomaia?**

No, il pernottamento e i pasti si pagano a parte con cifre molto contenute. Si deve inoltre aggiungere una piccola quota di iscrizione all'Istituto (20 euro), anche per fini assicurativi. Si ricorda che essendo un Istituto buddista i pasti sono vegetariani e vegani.

**Quali supporti didattici sono utilizzati durante il Corso?**

Alcuni materiali didattici utilizzati sono messi a disposizione su questo sito web. Non sono previste registrazioni data la delicatezza degli argomenti trattati e per favorire la partecipazione piena e spontanea dei corsisti.

**Quali verifiche di apprendimento sono previste?**

La verifica dell’apprendimento si articolerà in due fasi complementari:

1. **Attività in presenza**
   Durante il corso, ciascun partecipante – o piccoli gruppi, in base al numero di iscritti – sarà invitato a elaborare un piano personale di applicazione delle conoscenze acquisite, con riferimento sia alla propria attività professionale sia alla sfera personale. Questo piano sarà poi presentato al gruppo e discusso collegialmente, con il contributo sia dei partecipanti sia dei docenti, in un’ottica di apprendimento collaborativo e riflessivo.

2. **Verifica finale online per i crediti ECM**
   Ai fini dell’accreditamento ECM, è prevista una verifica dell’apprendimento tramite un questionario a risposta multipla, somministrato in modalità online. Questa prova è conforme agli standard richiesti dal sistema ECM nazionale.

**Come si raggiunge Pomaia?**

*Treno* La stazione più vicina a Pomaia, dove si trova l'Istituto, è Rosignano, in cui si arriva con i treni regionali. I treni più veloci fermano a Cecina, che dista 20 km circa. 

Su richiesta all'Istituto è possibile prenotare una navetta da Rosignano a Pomaia (e viceversa).

*Auto* Come raggiungere Pomaia in auto:

- Per chi arriva da sud: imboccare la Strada Statale SS206 direzione Pisa. Passata la località Badie, all’altezza di una sopraelevata, girare a destra in prossimità dell’indicazione per Pomaia o per Knauf. Proseguire per 7 km. Poche centinaia di metri prima di arrivare in paese a Pomaia, girare a destra in prossimità di una strada sterrata caratterizzata da un arco tibetano all’imbocco.

- Per chi arrva da nord: imboccare la Strada Statale SS206 direzione Cecina-Roma, a circa 12 km da Cecina, all’altezza di una sopraelevata, girare a sinistra in prossimità dell’indicazione per Pomaia o per Knauf. Proseguire per 7 km. Poche centinaia di metri prima di arrivare in paese a Pomaia, girare a destra in prossimità di una strada sterrata caratterizzata da un arco tibetano all’imbocco.

*Negli anni passati, sono stati spesso organizzati gruppi per condividere il viaggio in auto.*

GPS 43.430514 10.558944


