---
title: "Informazioni sui docenti"
format: html 
toc: true
toc-location: left
---


## Silverio Zucchi

1. Silverio Zucchi, psicologo, psicoterapeuta si occupa di psicoterapia con
adolescenti, giovani-adulti e adulti. Svolge attività come psicologo scolastico
presso diversi Istituti Superiori della città di Parma.

2. Silverio Zucchi, interista, il che la dice lunga sul suo temperamento di base,
quando non è impegnato a litigare con sé stesso si occupa di attività clinica,
psicologia scolastica e psicoterapia con adulti, giovani-adulti e adolescenti,
prevalentemente per imparare a prendersi cura di sé stesso e degli altri.
Consapevole si tratterà di un lavoro lungo che lo impegnerà per quasi tutta la
vita, collabora da numerosi anni anche con Fondazione Ceis onlus,
occupandosi di un Programma Ambulatoriale per consumatori di Cocaina: non
si sa mai. In generale vuole bene ai suoi pazienti, ma quando non ne può più (o
loro non ne possono più di lui), svolge attività come formatore presso alcuni
enti e società di servizi di formazione della città di Parma, occupandosi
prevalentemente di comunicazione e gestione dello stress.

Collabora con Fondazione Ceis Onlus, presso la quale ha gestito per numerosi
    anni un Programma Ambulatoriale per consumatori di Cocaina e per la quale
    svolge consulenze per consumatori di sostanze e formazione. Svolge attività
    come docente presso ASCCO – Accademia di specializzazione in Scienze
    Comportamentali e Cognitive e presso Humanitas, Scuola quadriennale di
    specializzazione in psicoterapia, e come formatore presso enti, società di
    servizi e Università, occupandosi prevalentemente di gestione dello stress e di
    mindfulness.

Membro fondatore di ACT Italia - Italian Chapter Association for Contextual
Behavioral Science (ACBS), è impegnato attivamente nello studio, nella ricerca e
nell’utilizzo clinico dell’Acceptance and Committment Therapy dal 2007, della
Compassion Focused Therapy e di altri approcci di terza generazione.

## [Giovanni Zucchi](https://interazioniumane.it/docenti/giovanni-zucchi/)

## [Constance Miller](https://www.linkedin.com/in/constance-miller-2a42268/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=it)

## [Joan Dombon](https://www.iltk.org/insegnante/joan-dombon/)

## Massimo Gusmano

formatore Deep Mindfulness e Counseling Si occupa da più di 30 anni di formazione, counseling e
crescita personale nelle organizzazioni pubbliche ed in ambito privato. E’ da anni praticante del
Buddhismo Mahayana ed attivo sostenitore dell’integrazione tra psicologia occidentale ed
insegnamento buddhista. Master in PNL e in Breathwork, è specializzato in psicosociologia
dell’organizzazione, analisi transazionale ed in counseling a mediazione corporea. Foundation course
nella “Core Process Psychotherapy” (Karuna Institute – England). Collabora da diversi anni con Il filo
del Sé proponendo seminari e corsi online. E’ ricercatore, docente e socio fondatore del gruppo di
ricerca ed evoluzione spirituale “Kenosis”. Fa parte del comitato direttivo dell’Associazione
Mindfulness Project e docente della scuola counseling. Ha incarichi di docenza in alcuni Master
Universitari (Padova, Bologna, Firenze).

## [Elisa Ruggeri](https://www.facebook.com/IstitutoOncologicoRomagnolo/videos/pratiche-di-mindfulness-con-elisa-ruggeri/348969156554307/)

è una psicologa e psicoterapeuta con una consolidata esperienza nell’ambito della psiconcologia, del sostegno alle vittime di violenza e della promozione del benessere psicologico nelle scuole. Dal 2006 lavora presso l’Istituto Oncologico Romagnolo, affiancando pazienti oncologici e familiari, e collabora con il centro antiviolenza “Rompi il Silenzio” e diverse realtà del territorio. Conduce percorsi di mindfulness, gruppi di supporto e attività formative, integrando competenze cliniche, educative e forensi.

## Marcella Langella 

Infermiera pediatrica, educatrice nido infanzia, insegnante internazionale di Yoga e
meditazione della tradizione Himalayana, 800h presso HYI di Firenze, insegnante del
massaggio infantile AIMI e Shantala per il bambino piccolo e grande e di baby yoga,
operatrice di primo livello di musica in culla formata presso “Scuola Popolare di Musica
Donna Olimpia” di Roma, master Reiki metodo Usui, perfezionamento post universitario in
meditazione, compassione e gestione emozionale nelle relazioni di aiuto presso Università
degli studi di Firenze.

Ha svolto il ruolo di co-ideatrice del primo corso di formazione per il personale sanitario
della “care” del prematuro presso il CNR (Centro Neonati a Rischio) dell’Istituto Giannina
Gaslini di Genova.

Ha svolto il ruolo di ideatrice e relatrice di alcuni progetti elaborati con i gruppi di lavoro dei
servizi educativi:

- “Il tocco buono”, laboratorio di massaggio infantile e baby yoga a Genova presso
l’asilo nido Villa Stalder;
- Laboratorio e formazione di “baby yoga” presso l’asilo di infanzia di Rapallo;
- “L’abbraccio colorato” laboratorio per le famiglie e formazione del personale, in
collaborazione con l’università di Torino, Dipartimento di Antropologia;
- Baby yoga, meditazione e massaggio infantile presso il nido di infanzia di Santa
Margherita Ligure.

Nel corso degli anni ha collaborato alla stesura di un documentario, articoli, inserti su
riviste riguardanti le esperienze svolte con i gruppi di bambini, genitori e operatori.
Da anni si occupa di formare il personale dei servizi educativi.

Dal 1984 sviluppa esperienza in ospedale, in particolare nell’ambito neonatale in terapia
sub-intensiva, sala parto, nido UNOC dell’ospedale San Martino di Genova, al CNR
dell’Istituto G. Gaslini di Genova e in maternità nei centri della riviera ligure e nei servizi
educativi presso gli asili di infanzia di Genova, Santa Margherita Ligure e Rapallo.

## [Claudio Sica](https://www.unifi.it/p-doc2-2023-0-A-2c2a342f382e-0.html)

## [Corrado Caudek](https://www.unifi.it/p-doc2-0-0-A-3f2b342938302a-0.html)

## [Ilaria Colpizzi](https://dsv.units.it/it/dipartimento/persone/assegnisti-di-ricerca?q=it/node/62082)

